language: python

sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - python setup.py install
  - pip install pytest

script:
  - python setup.py test

notifications:
  email:
    on_success: change
    on_failure: change
